repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check
        args: ["--no-fix"]
        language: system
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        args: ["--check"]
        language: system
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: poetry run mypy src/pg_stage/.
        args: ["--ignore-missing-imports"]
        language: system
        types: [python]
        pass_filenames: false
